# path: book-service/src/main/resources/application.properties
# purpose: cấu hình cổng chạy và kết nối database cho book-service (sách + thể loại)

spring.application.name=book-service
server.port=8082

spring.datasource.url=jdbc:mysql://localhost:3306/lib_book_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh
spring.datasource.username=root
spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# phải GIỐNG HỆT jwt.secret của auth-service
jwt.secret=Library-Microservices-Secret-Key-Bai-Tap-Lon-SOA-2026-Quan-Ly-Thu-Vien
